# Generated by Django 5.1.7 on 2025-03-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('published_date', models.DateField(auto_now=True)),
                ('category', models.CharField(max_length=25)),
                ('video', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
