# Generated by Django 5.1.7 on 2025-04-01 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos_display', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Videos',
            new_name='Video',
        ),
    ]
