# Generated by Django 5.1.7 on 2025-08-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_display', '0007_rename_view_saved_video_watchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
